//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHiHiBook.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int UserID { get; set; }
        [Required(ErrorMessage = "Please enter your username!")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Please enter your password!")]
        [DataType(DataType.Password)]
        public string Pass { get; set; }
        [Required(ErrorMessage = "Please enter your first name!")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Please enter your last name!")]
        public string LastName { get; set; }
        public string Addr { get; set; }
        [Required(ErrorMessage = "Please enter your email!")]
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<int> MembershipID { get; set; }
        [Required(ErrorMessage = "Error confirm password!")]
        [Compare("Pass")]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }
    
        public virtual Membership Membership { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }

        public string LogInErrorMessage { get; set; }
    }
}
